// Auto-generated barrel — imports and registers all icons.
// Used by Storybook and dev tools. NOT for production consumers.
// Re-generate: node source/components/icon/generate-icon-entries.js

import { registerIcon } from '../icon-registry.js';

import { airplaySvg } from './entries/airplay.js';
import { alarmClockSvg } from './entries/alarm-clock.js';
import { alignHorizontalSvg } from './entries/align-horizontal.js';
import { alignVerticalSvg } from './entries/align-vertical.js';
import { angleSvg } from './entries/angle.js';
import { archiveSvg } from './entries/archive.js';
import { arrowBottomLeftSvg } from './entries/arrow-bottom-left.js';
import { arrowBottomRightSvg } from './entries/arrow-bottom-right.js';
import { arrowDownSvg } from './entries/arrow-down.js';
import { arrowDownCircleSvg } from './entries/arrow-down-circle.js';
import { arrowLeftSvg } from './entries/arrow-left.js';
import { arrowLeftCircleSvg } from './entries/arrow-left-circle.js';
import { arrowRightSvg } from './entries/arrow-right.js';
import { arrowRightCircleSvg } from './entries/arrow-right-circle.js';
import { arrowTopLeftSvg } from './entries/arrow-top-left.js';
import { arrowTopRightSvg } from './entries/arrow-top-right.js';
import { arrowUpSvg } from './entries/arrow-up.js';
import { arrowUpCircleSvg } from './entries/arrow-up-circle.js';
import { audioWaveSvg } from './entries/audio-wave.js';
import { backspaceSvg } from './entries/backspace.js';
import { backwardSvg } from './entries/backward.js';
import { bagSvg } from './entries/bag.js';
import { battery75Svg } from './entries/battery-75.js';
import { batteryChargingSvg } from './entries/battery-charging.js';
import { batteryEmptySvg } from './entries/battery-empty.js';
import { batteryFullSvg } from './entries/battery-full.js';
import { batteryHalfSvg } from './entries/battery-half.js';
import { batteryLowSvg } from './entries/battery-low.js';
import { bellSvg } from './entries/bell.js';
import { bellDisabledSvg } from './entries/bell-disabled.js';
import { bellRingingSvg } from './entries/bell-ringing.js';
import { bellSnoozeSvg } from './entries/bell-snooze.js';
import { bluetoothSvg } from './entries/bluetooth.js';
import { bookSvg } from './entries/book.js';
import { bookClosedSvg } from './entries/book-closed.js';
import { bookTextSvg } from './entries/book-text.js';
import { bookmarkSvg } from './entries/bookmark.js';
import { bookmarkBookSvg } from './entries/bookmark-book.js';
import { boxSvg } from './entries/box.js';
import { boxAddSvg } from './entries/box-add.js';
import { boxDownloadSvg } from './entries/box-download.js';
import { boxOpenSvg } from './entries/box-open.js';
import { boxRemoveSvg } from './entries/box-remove.js';
import { boxesSvg } from './entries/boxes.js';
import { branchSvg } from './entries/branch.js';
import { briefcaseSvg } from './entries/briefcase.js';
import { browserSvg } from './entries/browser.js';
import { browserAltSvg } from './entries/browser-alt.js';
import { buttonAddSvg } from './entries/button-add.js';
import { buttonMinusSvg } from './entries/button-minus.js';
import { calculatorSvg } from './entries/calculator.js';
import { calendarSvg } from './entries/calendar.js';
import { calendarAddSvg } from './entries/calendar-add.js';
import { calendarDateSvg } from './entries/calendar-date.js';
import { calendarDaySvg } from './entries/calendar-day.js';
import { calendarDaysSvg } from './entries/calendar-days.js';
import { calendarLastDaySvg } from './entries/calendar-last-day.js';
import { calendarMonthSvg } from './entries/calendar-month.js';
import { calendarMoveSvg } from './entries/calendar-move.js';
import { calendarRemoveSvg } from './entries/calendar-remove.js';
import { calendarSplitSvg } from './entries/calendar-split.js';
import { calendarWeekSvg } from './entries/calendar-week.js';
import { cameraSvg } from './entries/camera.js';
import { cameraAltSvg } from './entries/camera-alt.js';
import { cameraNoflashSvg } from './entries/camera-noflash.js';
import { cameraNoflashAltSvg } from './entries/camera-noflash-alt.js';
import { captureSvg } from './entries/capture.js';
import { cardTimelineSvg } from './entries/card-timeline.js';
import { cardViewSvg } from './entries/card-view.js';
import { carouselSvg } from './entries/carousel.js';
import { cartSvg } from './entries/cart.js';
import { castSvg } from './entries/cast.js';
import { chainSvg } from './entries/chain.js';
import { chatAddSvg } from './entries/chat-add.js';
import { checkSvg } from './entries/check.js';
import { checkCircleSvg } from './entries/check-circle.js';
import { checkCircleOutsideSvg } from './entries/check-circle-outside.js';
import { checkboxCheckedSvg } from './entries/checkbox-checked.js';
import { checkboxEmptySvg } from './entries/checkbox-empty.js';
import { chevronCloseSvg } from './entries/chevron-close.js';
import { chevronDownSvg } from './entries/chevron-down.js';
import { chevronDownCircleSvg } from './entries/chevron-down-circle.js';
import { chevronDownDoubleSvg } from './entries/chevron-down-double.js';
import { chevronLeftSvg } from './entries/chevron-left.js';
import { chevronLeftCircleSvg } from './entries/chevron-left-circle.js';
import { chevronLeftDoubleSvg } from './entries/chevron-left-double.js';
import { chevronOpenSvg } from './entries/chevron-open.js';
import { chevronRightSvg } from './entries/chevron-right.js';
import { chevronRightCircleSvg } from './entries/chevron-right-circle.js';
import { chevronRightDoubleSvg } from './entries/chevron-right-double.js';
import { chevronUpSvg } from './entries/chevron-up.js';
import { chevronUpCircleSvg } from './entries/chevron-up-circle.js';
import { chevronUpDoubleSvg } from './entries/chevron-up-double.js';
import { circleSvg } from './entries/circle.js';
import { circleMenuSvg } from './entries/circle-menu.js';
import { circleSplitSvg } from './entries/circle-split.js';
import { clipboardSvg } from './entries/clipboard.js';
import { clipboardAddSvg } from './entries/clipboard-add.js';
import { clipboardCheckSvg } from './entries/clipboard-check.js';
import { clipboardCopySvg } from './entries/clipboard-copy.js';
import { clipboardCrossSvg } from './entries/clipboard-cross.js';
import { clipboardNotesSvg } from './entries/clipboard-notes.js';
import { clipboardRemoveSvg } from './entries/clipboard-remove.js';
import { clockSvg } from './entries/clock.js';
import { closeSvg } from './entries/close.js';
import { cloudSvg } from './entries/cloud.js';
import { cloudDisconnectSvg } from './entries/cloud-disconnect.js';
import { cloudDownloadSvg } from './entries/cloud-download.js';
import { cloudDownloadAltSvg } from './entries/cloud-download-alt.js';
import { cloudUploadSvg } from './entries/cloud-upload.js';
import { cloudUploadAltSvg } from './entries/cloud-upload-alt.js';
import { codeSvg } from './entries/code.js';
import { coffeeSvg } from './entries/coffee.js';
import { coinSvg } from './entries/coin.js';
import { coinsSvg } from './entries/coins.js';
import { compassSvg } from './entries/compass.js';
import { componentAddSvg } from './entries/component-add.js';
import { contactsSvg } from './entries/contacts.js';
import { contractSvg } from './entries/contract.js';
import { createSvg } from './entries/create.js';
import { creditCardSvg } from './entries/credit-card.js';
import { cropSvg } from './entries/crop.js';
import { crossSvg } from './entries/cross.js';
import { crossCircleSvg } from './entries/cross-circle.js';
import { crosshairSvg } from './entries/crosshair.js';
import { cubeSvg } from './entries/cube.js';
import { cubesSvg } from './entries/cubes.js';
import { cylinderSvg } from './entries/cylinder.js';
import { databaseSvg } from './entries/database.js';
import { diamondSvg } from './entries/diamond.js';
import { directionsSvg } from './entries/directions.js';
import { discSvg } from './entries/disc.js';
import { displaySvg } from './entries/display.js';
import { displayAltSvg } from './entries/display-alt.js';
import { documentSvg } from './entries/document.js';
import { documentJustifiedSvg } from './entries/document-justified.js';
import { documentListSvg } from './entries/document-list.js';
import { documentStackSvg } from './entries/document-stack.js';
import { documentWordsSvg } from './entries/document-words.js';
import { doorSvg } from './entries/door.js';
import { doorAltSvg } from './entries/door-alt.js';
import { downloadSvg } from './entries/download.js';
import { downloadAltSvg } from './entries/download-alt.js';
import { downwardSvg } from './entries/downward.js';
import { dragSvg } from './entries/drag.js';
import { dragCircleSvg } from './entries/drag-circle.js';
import { dragVerticalSvg } from './entries/drag-vertical.js';
import { duplicateSvg } from './entries/duplicate.js';
import { duplicateAltSvg } from './entries/duplicate-alt.js';
import { enterSvg } from './entries/enter.js';
import { enterAltSvg } from './entries/enter-alt.js';
import { episodesSvg } from './entries/episodes.js';
import { exitLeftSvg } from './entries/exit-left.js';
import { exitRightSvg } from './entries/exit-right.js';
import { expandSvg } from './entries/expand.js';
import { expandHeightSvg } from './entries/expand-height.js';
import { expandWidthSvg } from './entries/expand-width.js';
import { externalSvg } from './entries/external.js';
import { eyeSvg } from './entries/eye.js';
import { eyeClosedSvg } from './entries/eye-closed.js';
import { eyeNoSvg } from './entries/eye-no.js';
import { faceDelightedSvg } from './entries/face-delighted.js';
import { faceHappySvg } from './entries/face-happy.js';
import { faceNeutralSvg } from './entries/face-neutral.js';
import { faceSadSvg } from './entries/face-sad.js';
import { fileDownloadSvg } from './entries/file-download.js';
import { fileUploadSvg } from './entries/file-upload.js';
import { filesHistorySvg } from './entries/files-history.js';
import { filesMultiSvg } from './entries/files-multi.js';
import { filesStackSvg } from './entries/files-stack.js';
import { filmSvg } from './entries/film.js';
import { filterSvg } from './entries/filter.js';
import { filterCircleSvg } from './entries/filter-circle.js';
import { filterSingleSvg } from './entries/filter-single.js';
import { filteringSvg } from './entries/filtering.js';
import { fingerprintSvg } from './entries/fingerprint.js';
import { flagSvg } from './entries/flag.js';
import { flameSvg } from './entries/flame.js';
import { flameAltSvg } from './entries/flame-alt.js';
import { flipViewSvg } from './entries/flip-view.js';
import { floppySvg } from './entries/floppy.js';
import { folderAddSvg } from './entries/folder-add.js';
import { folderClosedSvg } from './entries/folder-closed.js';
import { folderMinusSvg } from './entries/folder-minus.js';
import { folderOpenSvg } from './entries/folder-open.js';
import { forkGitSvg } from './entries/fork-git.js';
import { forwardSvg } from './entries/forward.js';
import { frameSvg } from './entries/frame.js';
import { fullscreenSvg } from './entries/fullscreen.js';
import { funnelSvg } from './entries/funnel.js';
import { gaugeSvg } from './entries/gauge.js';
import { giftSvg } from './entries/gift.js';
import { globeSvg } from './entries/globe.js';
import { gpsSvg } from './entries/gps.js';
import { grabSvg } from './entries/grab.js';
import { graphBarSvg } from './entries/graph-bar.js';
import { graphBoxSvg } from './entries/graph-box.js';
import { graphIncreaseSvg } from './entries/graph-increase.js';
import { gridSvg } from './entries/grid.js';
import { gridCirclesSvg } from './entries/grid-circles.js';
import { gridCirclesAddSvg } from './entries/grid-circles-add.js';
import { gridSmallSvg } from './entries/grid-small.js';
import { gridSquaresSvg } from './entries/grid-squares.js';
import { gridSquaresAddSvg } from './entries/grid-squares-add.js';
import { handSvg } from './entries/hand.js';
import { harddriveSvg } from './entries/harddrive.js';
import { hashSvg } from './entries/hash.js';
import { heartSvg } from './entries/heart.js';
import { heartRateSvg } from './entries/heart-rate.js';
import { heartRemoveSvg } from './entries/heart-remove.js';
import { heightSvg } from './entries/height.js';
import { hierarchySvg } from './entries/hierarchy.js';
import { homeSvg } from './entries/home.js';
import { homeAltSvg } from './entries/home-alt.js';
import { homeCheckSvg } from './entries/home-check.js';
import { homeDoorSvg } from './entries/home-door.js';
import { importSvg } from './entries/import.js';
import { inboxSvg } from './entries/inbox.js';
import { inboxAltSvg } from './entries/inbox-alt.js';
import { infoCircleSvg } from './entries/info-circle.js';
import { iphoneLandscapeSvg } from './entries/iphone-landscape.js';
import { iphonePortraitSvg } from './entries/iphone-portrait.js';
import { jumpBackwardSvg } from './entries/jump-backward.js';
import { jumpForwardSvg } from './entries/jump-forward.js';
import { jumpLeftSvg } from './entries/jump-left.js';
import { jumpRightSvg } from './entries/jump-right.js';
import { keyboardSvg } from './entries/keyboard.js';
import { laptopSvg } from './entries/laptop.js';
import { lightbulbSvg } from './entries/lightbulb.js';
import { lightbulbOnSvg } from './entries/lightbulb-on.js';
import { lightningSvg } from './entries/lightning.js';
import { lightningAltSvg } from './entries/lightning-alt.js';
import { lineweightSvg } from './entries/lineweight.js';
import { linkSvg } from './entries/link.js';
import { linkAltSvg } from './entries/link-alt.js';
import { linkBrokenSvg } from './entries/link-broken.js';
import { linkHorizontalSvg } from './entries/link-horizontal.js';
import { linkVerticalSvg } from './entries/link-vertical.js';
import { listSvg } from './entries/list.js';
import { listAddSvg } from './entries/list-add.js';
import { listNumberedSvg } from './entries/list-numbered.js';
import { loaderSvg } from './entries/loader.js';
import { locationSvg } from './entries/location.js';
import { lockSvg } from './entries/lock.js';
import { lockOpenSvg } from './entries/lock-open.js';
import { mailSvg } from './entries/mail.js';
import { mailAddSvg } from './entries/mail-add.js';
import { mailDeleteSvg } from './entries/mail-delete.js';
import { mailMinusSvg } from './entries/mail-minus.js';
import { mailNewSvg } from './entries/mail-new.js';
import { mailOpenSvg } from './entries/mail-open.js';
import { mailRemoveSvg } from './entries/mail-remove.js';
import { marqueeSvg } from './entries/marquee.js';
import { maximiseSvg } from './entries/maximise.js';
import { menuHamburgerSvg } from './entries/menu-hamburger.js';
import { menuHorizontalSvg } from './entries/menu-horizontal.js';
import { menuVerticalSvg } from './entries/menu-vertical.js';
import { messageSvg } from './entries/message.js';
import { messageWritingSvg } from './entries/message-writing.js';
import { microphoneSvg } from './entries/microphone.js';
import { microphoneDisabledSvg } from './entries/microphone-disabled.js';
import { microphoneMutedSvg } from './entries/microphone-muted.js';
import { midpointSvg } from './entries/midpoint.js';
import { miniPlayerSvg } from './entries/mini-player.js';
import { minimiseSvg } from './entries/minimise.js';
import { minusSvg } from './entries/minus.js';
import { minusCircleSvg } from './entries/minus-circle.js';
import { moonSvg } from './entries/moon.js';
import { moveSvg } from './entries/move.js';
import { newspaperSvg } from './entries/newspaper.js';
import { noSignSvg } from './entries/no-sign.js';
import { notebookSvg } from './entries/notebook.js';
import { notificationSvg } from './entries/notification.js';
import { nutSvg } from './entries/nut.js';
import { pagesSvg } from './entries/pages.js';
import { panelBottomSvg } from './entries/panel-bottom.js';
import { panelCenterSvg } from './entries/panel-center.js';
import { panelLeftSvg } from './entries/panel-left.js';
import { panelRightSvg } from './entries/panel-right.js';
import { panelSectionedSvg } from './entries/panel-sectioned.js';
import { panelTopSvg } from './entries/panel-top.js';
import { paperSvg } from './entries/paper.js';
import { paperFoldedSvg } from './entries/paper-folded.js';
import { paperPlaneSvg } from './entries/paper-plane.js';
import { paperPlaneAltSvg } from './entries/paper-plane-alt.js';
import { paperclipSvg } from './entries/paperclip.js';
import { paragraphCenterSvg } from './entries/paragraph-center.js';
import { paragraphEndSvg } from './entries/paragraph-end.js';
import { paragraphLeftSvg } from './entries/paragraph-left.js';
import { paragraphRightSvg } from './entries/paragraph-right.js';
import { paragraphStartSvg } from './entries/paragraph-start.js';
import { penSvg } from './entries/pen.js';
import { phoneLandscapeSvg } from './entries/phone-landscape.js';
import { phonePortraitSvg } from './entries/phone-portrait.js';
import { pictureSvg } from './entries/picture.js';
import { pieHalfSvg } from './entries/pie-half.js';
import { pieQuarterSvg } from './entries/pie-quarter.js';
import { pieThirdSvg } from './entries/pie-third.js';
import { pillSvg } from './entries/pill.js';
import { playButtonSvg } from './entries/play-button.js';
import { plusSvg } from './entries/plus.js';
import { plusCircleSvg } from './entries/plus-circle.js';
import { postcardSvg } from './entries/postcard.js';
import { printerSvg } from './entries/printer.js';
import { projectorSvg } from './entries/projector.js';
import { pullDownSvg } from './entries/pull-down.js';
import { pullLeftSvg } from './entries/pull-left.js';
import { pullRightSvg } from './entries/pull-right.js';
import { pullUpSvg } from './entries/pull-up.js';
import { pushDownSvg } from './entries/push-down.js';
import { pushLeftSvg } from './entries/push-left.js';
import { pushRightSvg } from './entries/push-right.js';
import { pushUpSvg } from './entries/push-up.js';
import { questionCircleSvg } from './entries/question-circle.js';
import { radioOnSvg } from './entries/radio-on.js';
import { receiptSvg } from './entries/receipt.js';
import { recordSvg } from './entries/record.js';
import { redoSvg } from './entries/redo.js';
import { refreshSvg } from './entries/refresh.js';
import { refreshAltSvg } from './entries/refresh-alt.js';
import { replicateSvg } from './entries/replicate.js';
import { replicateAltSvg } from './entries/replicate-alt.js';
import { resetSvg } from './entries/reset.js';
import { resetAltSvg } from './entries/reset-alt.js';
import { resetForwardSvg } from './entries/reset-forward.js';
import { resetHardSvg } from './entries/reset-hard.js';
import { resetTemporarySvg } from './entries/reset-temporary.js';
import { retweetSvg } from './entries/retweet.js';
import { reuseSvg } from './entries/reuse.js';
import { reverseSvg } from './entries/reverse.js';
import { reverseAltSvg } from './entries/reverse-alt.js';
import { revertSvg } from './entries/revert.js';
import { rocketSvg } from './entries/rocket.js';
import { rulerSvg } from './entries/ruler.js';
import { scaleSvg } from './entries/scale.js';
import { scaleContractSvg } from './entries/scale-contract.js';
import { scaleExtendSvg } from './entries/scale-extend.js';
import { scalpelSvg } from './entries/scalpel.js';
import { searchSvg } from './entries/search.js';
import { serverSvg } from './entries/server.js';
import { settingsSvg } from './entries/settings.js';
import { shareSvg } from './entries/share.js';
import { shareAltSvg } from './entries/share-alt.js';
import { shuffleSvg } from './entries/shuffle.js';
import { sideMenuSvg } from './entries/side-menu.js';
import { signalFullSvg } from './entries/signal-full.js';
import { signalLowSvg } from './entries/signal-low.js';
import { signalMediumSvg } from './entries/signal-medium.js';
import { signalNoneSvg } from './entries/signal-none.js';
import { slashBackwardSvg } from './entries/slash-backward.js';
import { slashForwardSvg } from './entries/slash-forward.js';
import { slidersSvg } from './entries/sliders.js';
import { sortSvg } from './entries/sort.js';
import { sortAltSvg } from './entries/sort-alt.js';
import { speakerSvg } from './entries/speaker.js';
import { speechBubbleSvg } from './entries/speech-bubble.js';
import { speechTypingSvg } from './entries/speech-typing.js';
import { splitSvg } from './entries/split.js';
import { splitThreeSvg } from './entries/split-three.js';
import { starSvg } from './entries/star.js';
import { sunSvg } from './entries/sun.js';
import { supportSvg } from './entries/support.js';
import { swapSvg } from './entries/swap.js';
import { switchSvg } from './entries/switch.js';
import { tableSvg } from './entries/table.js';
import { tableHeaderSvg } from './entries/table-header.js';
import { tagSvg } from './entries/tag.js';
import { tagMilestoneSvg } from './entries/tag-milestone.js';
import { tagsSvg } from './entries/tags.js';
import { targetSvg } from './entries/target.js';
import { terminalSvg } from './entries/terminal.js';
import { threadSvg } from './entries/thread.js';
import { thumbsDownSvg } from './entries/thumbs-down.js';
import { thumbsUpSvg } from './entries/thumbs-up.js';
import { ticketSvg } from './entries/ticket.js';
import { timelineSvg } from './entries/timeline.js';
import { todoSvg } from './entries/todo.js';
import { toggleSvg } from './entries/toggle.js';
import { togglesSvg } from './entries/toggles.js';
import { translateSvg } from './entries/translate.js';
import { trashSvg } from './entries/trash.js';
import { trashAltSvg } from './entries/trash-alt.js';
import { trophySvg } from './entries/trophy.js';
import { tvModeSvg } from './entries/tv-mode.js';
import { unarchiveSvg } from './entries/unarchive.js';
import { undoSvg } from './entries/undo.js';
import { undoHistorySvg } from './entries/undo-history.js';
import { unlinkHorizontalSvg } from './entries/unlink-horizontal.js';
import { unlinkVerticalSvg } from './entries/unlink-vertical.js';
import { uploadSvg } from './entries/upload.js';
import { uploadAltSvg } from './entries/upload-alt.js';
import { upwardSvg } from './entries/upward.js';
import { userSvg } from './entries/user.js';
import { userAddSvg } from './entries/user-add.js';
import { userCircleSvg } from './entries/user-circle.js';
import { userMaleSvg } from './entries/user-male.js';
import { userMaleCircleSvg } from './entries/user-male-circle.js';
import { userRemoveSvg } from './entries/user-remove.js';
import { usersSvg } from './entries/users.js';
import { vennSvg } from './entries/venn.js';
import { versionSvg } from './entries/version.js';
import { versionsSvg } from './entries/versions.js';
import { videoSvg } from './entries/video.js';
import { volume0Svg } from './entries/volume-0.js';
import { volumeAddSvg } from './entries/volume-add.js';
import { volumeDisabledSvg } from './entries/volume-disabled.js';
import { volumeHighSvg } from './entries/volume-high.js';
import { volumeLowSvg } from './entries/volume-low.js';
import { volumeMinusSvg } from './entries/volume-minus.js';
import { volumeMutedSvg } from './entries/volume-muted.js';
import { walletSvg } from './entries/wallet.js';
import { warningCircleSvg } from './entries/warning-circle.js';
import { warningHexSvg } from './entries/warning-hex.js';
import { warningTriangleSvg } from './entries/warning-triangle.js';
import { wavesSvg } from './entries/waves.js';
import { widthSvg } from './entries/width.js';
import { wifiSvg } from './entries/wifi.js';
import { wifiErrorSvg } from './entries/wifi-error.js';
import { wifiNoneSvg } from './entries/wifi-none.js';
import { windowSvg } from './entries/window.js';
import { windowCollapseLeftSvg } from './entries/window-collapse-left.js';
import { windowCollapseRightSvg } from './entries/window-collapse-right.js';
import { windowContentSvg } from './entries/window-content.js';
import { wrapBackSvg } from './entries/wrap-back.js';
import { wrapForwardSvg } from './entries/wrap-forward.js';
import { writeSvg } from './entries/write.js';
import { zoomCancelSvg } from './entries/zoom-cancel.js';
import { zoomInSvg } from './entries/zoom-in.js';
import { zoomOutSvg } from './entries/zoom-out.js';
import { zoomResetSvg } from './entries/zoom-reset.js';

  registerIcon('airplay', airplaySvg);
  registerIcon('alarm-clock', alarmClockSvg);
  registerIcon('align-horizontal', alignHorizontalSvg);
  registerIcon('align-vertical', alignVerticalSvg);
  registerIcon('angle', angleSvg);
  registerIcon('archive', archiveSvg);
  registerIcon('arrow-bottom-left', arrowBottomLeftSvg);
  registerIcon('arrow-bottom-right', arrowBottomRightSvg);
  registerIcon('arrow-down', arrowDownSvg);
  registerIcon('arrow-down-circle', arrowDownCircleSvg);
  registerIcon('arrow-left', arrowLeftSvg);
  registerIcon('arrow-left-circle', arrowLeftCircleSvg);
  registerIcon('arrow-right', arrowRightSvg);
  registerIcon('arrow-right-circle', arrowRightCircleSvg);
  registerIcon('arrow-top-left', arrowTopLeftSvg);
  registerIcon('arrow-top-right', arrowTopRightSvg);
  registerIcon('arrow-up', arrowUpSvg);
  registerIcon('arrow-up-circle', arrowUpCircleSvg);
  registerIcon('audio-wave', audioWaveSvg);
  registerIcon('backspace', backspaceSvg);
  registerIcon('backward', backwardSvg);
  registerIcon('bag', bagSvg);
  registerIcon('battery-75', battery75Svg);
  registerIcon('battery-charging', batteryChargingSvg);
  registerIcon('battery-empty', batteryEmptySvg);
  registerIcon('battery-full', batteryFullSvg);
  registerIcon('battery-half', batteryHalfSvg);
  registerIcon('battery-low', batteryLowSvg);
  registerIcon('bell', bellSvg);
  registerIcon('bell-disabled', bellDisabledSvg);
  registerIcon('bell-ringing', bellRingingSvg);
  registerIcon('bell-snooze', bellSnoozeSvg);
  registerIcon('bluetooth', bluetoothSvg);
  registerIcon('book', bookSvg);
  registerIcon('book-closed', bookClosedSvg);
  registerIcon('book-text', bookTextSvg);
  registerIcon('bookmark', bookmarkSvg);
  registerIcon('bookmark-book', bookmarkBookSvg);
  registerIcon('box', boxSvg);
  registerIcon('box-add', boxAddSvg);
  registerIcon('box-download', boxDownloadSvg);
  registerIcon('box-open', boxOpenSvg);
  registerIcon('box-remove', boxRemoveSvg);
  registerIcon('boxes', boxesSvg);
  registerIcon('branch', branchSvg);
  registerIcon('briefcase', briefcaseSvg);
  registerIcon('browser', browserSvg);
  registerIcon('browser-alt', browserAltSvg);
  registerIcon('button-add', buttonAddSvg);
  registerIcon('button-minus', buttonMinusSvg);
  registerIcon('calculator', calculatorSvg);
  registerIcon('calendar', calendarSvg);
  registerIcon('calendar-add', calendarAddSvg);
  registerIcon('calendar-date', calendarDateSvg);
  registerIcon('calendar-day', calendarDaySvg);
  registerIcon('calendar-days', calendarDaysSvg);
  registerIcon('calendar-last-day', calendarLastDaySvg);
  registerIcon('calendar-month', calendarMonthSvg);
  registerIcon('calendar-move', calendarMoveSvg);
  registerIcon('calendar-remove', calendarRemoveSvg);
  registerIcon('calendar-split', calendarSplitSvg);
  registerIcon('calendar-week', calendarWeekSvg);
  registerIcon('camera', cameraSvg);
  registerIcon('camera-alt', cameraAltSvg);
  registerIcon('camera-noflash', cameraNoflashSvg);
  registerIcon('camera-noflash-alt', cameraNoflashAltSvg);
  registerIcon('capture', captureSvg);
  registerIcon('card-timeline', cardTimelineSvg);
  registerIcon('card-view', cardViewSvg);
  registerIcon('carousel', carouselSvg);
  registerIcon('cart', cartSvg);
  registerIcon('cast', castSvg);
  registerIcon('chain', chainSvg);
  registerIcon('chat-add', chatAddSvg);
  registerIcon('check', checkSvg);
  registerIcon('check-circle', checkCircleSvg);
  registerIcon('check-circle-outside', checkCircleOutsideSvg);
  registerIcon('checkbox-checked', checkboxCheckedSvg);
  registerIcon('checkbox-empty', checkboxEmptySvg);
  registerIcon('chevron-close', chevronCloseSvg);
  registerIcon('chevron-down', chevronDownSvg);
  registerIcon('chevron-down-circle', chevronDownCircleSvg);
  registerIcon('chevron-down-double', chevronDownDoubleSvg);
  registerIcon('chevron-left', chevronLeftSvg);
  registerIcon('chevron-left-circle', chevronLeftCircleSvg);
  registerIcon('chevron-left-double', chevronLeftDoubleSvg);
  registerIcon('chevron-open', chevronOpenSvg);
  registerIcon('chevron-right', chevronRightSvg);
  registerIcon('chevron-right-circle', chevronRightCircleSvg);
  registerIcon('chevron-right-double', chevronRightDoubleSvg);
  registerIcon('chevron-up', chevronUpSvg);
  registerIcon('chevron-up-circle', chevronUpCircleSvg);
  registerIcon('chevron-up-double', chevronUpDoubleSvg);
  registerIcon('circle', circleSvg);
  registerIcon('circle-menu', circleMenuSvg);
  registerIcon('circle-split', circleSplitSvg);
  registerIcon('clipboard', clipboardSvg);
  registerIcon('clipboard-add', clipboardAddSvg);
  registerIcon('clipboard-check', clipboardCheckSvg);
  registerIcon('clipboard-copy', clipboardCopySvg);
  registerIcon('clipboard-cross', clipboardCrossSvg);
  registerIcon('clipboard-notes', clipboardNotesSvg);
  registerIcon('clipboard-remove', clipboardRemoveSvg);
  registerIcon('clock', clockSvg);
  registerIcon('close', closeSvg);
  registerIcon('cloud', cloudSvg);
  registerIcon('cloud-disconnect', cloudDisconnectSvg);
  registerIcon('cloud-download', cloudDownloadSvg);
  registerIcon('cloud-download-alt', cloudDownloadAltSvg);
  registerIcon('cloud-upload', cloudUploadSvg);
  registerIcon('cloud-upload-alt', cloudUploadAltSvg);
  registerIcon('code', codeSvg);
  registerIcon('coffee', coffeeSvg);
  registerIcon('coin', coinSvg);
  registerIcon('coins', coinsSvg);
  registerIcon('compass', compassSvg);
  registerIcon('component-add', componentAddSvg);
  registerIcon('contacts', contactsSvg);
  registerIcon('contract', contractSvg);
  registerIcon('create', createSvg);
  registerIcon('credit-card', creditCardSvg);
  registerIcon('crop', cropSvg);
  registerIcon('cross', crossSvg);
  registerIcon('cross-circle', crossCircleSvg);
  registerIcon('crosshair', crosshairSvg);
  registerIcon('cube', cubeSvg);
  registerIcon('cubes', cubesSvg);
  registerIcon('cylinder', cylinderSvg);
  registerIcon('database', databaseSvg);
  registerIcon('diamond', diamondSvg);
  registerIcon('directions', directionsSvg);
  registerIcon('disc', discSvg);
  registerIcon('display', displaySvg);
  registerIcon('display-alt', displayAltSvg);
  registerIcon('document', documentSvg);
  registerIcon('document-justified', documentJustifiedSvg);
  registerIcon('document-list', documentListSvg);
  registerIcon('document-stack', documentStackSvg);
  registerIcon('document-words', documentWordsSvg);
  registerIcon('door', doorSvg);
  registerIcon('door-alt', doorAltSvg);
  registerIcon('download', downloadSvg);
  registerIcon('download-alt', downloadAltSvg);
  registerIcon('downward', downwardSvg);
  registerIcon('drag', dragSvg);
  registerIcon('drag-circle', dragCircleSvg);
  registerIcon('drag-vertical', dragVerticalSvg);
  registerIcon('duplicate', duplicateSvg);
  registerIcon('duplicate-alt', duplicateAltSvg);
  registerIcon('enter', enterSvg);
  registerIcon('enter-alt', enterAltSvg);
  registerIcon('episodes', episodesSvg);
  registerIcon('exit-left', exitLeftSvg);
  registerIcon('exit-right', exitRightSvg);
  registerIcon('expand', expandSvg);
  registerIcon('expand-height', expandHeightSvg);
  registerIcon('expand-width', expandWidthSvg);
  registerIcon('external', externalSvg);
  registerIcon('eye', eyeSvg);
  registerIcon('eye-closed', eyeClosedSvg);
  registerIcon('eye-no', eyeNoSvg);
  registerIcon('face-delighted', faceDelightedSvg);
  registerIcon('face-happy', faceHappySvg);
  registerIcon('face-neutral', faceNeutralSvg);
  registerIcon('face-sad', faceSadSvg);
  registerIcon('file-download', fileDownloadSvg);
  registerIcon('file-upload', fileUploadSvg);
  registerIcon('files-history', filesHistorySvg);
  registerIcon('files-multi', filesMultiSvg);
  registerIcon('files-stack', filesStackSvg);
  registerIcon('film', filmSvg);
  registerIcon('filter', filterSvg);
  registerIcon('filter-circle', filterCircleSvg);
  registerIcon('filter-single', filterSingleSvg);
  registerIcon('filtering', filteringSvg);
  registerIcon('fingerprint', fingerprintSvg);
  registerIcon('flag', flagSvg);
  registerIcon('flame', flameSvg);
  registerIcon('flame-alt', flameAltSvg);
  registerIcon('flip-view', flipViewSvg);
  registerIcon('floppy', floppySvg);
  registerIcon('folder-add', folderAddSvg);
  registerIcon('folder-closed', folderClosedSvg);
  registerIcon('folder-minus', folderMinusSvg);
  registerIcon('folder-open', folderOpenSvg);
  registerIcon('fork-git', forkGitSvg);
  registerIcon('forward', forwardSvg);
  registerIcon('frame', frameSvg);
  registerIcon('fullscreen', fullscreenSvg);
  registerIcon('funnel', funnelSvg);
  registerIcon('gauge', gaugeSvg);
  registerIcon('gift', giftSvg);
  registerIcon('globe', globeSvg);
  registerIcon('gps', gpsSvg);
  registerIcon('grab', grabSvg);
  registerIcon('graph-bar', graphBarSvg);
  registerIcon('graph-box', graphBoxSvg);
  registerIcon('graph-increase', graphIncreaseSvg);
  registerIcon('grid', gridSvg);
  registerIcon('grid-circles', gridCirclesSvg);
  registerIcon('grid-circles-add', gridCirclesAddSvg);
  registerIcon('grid-small', gridSmallSvg);
  registerIcon('grid-squares', gridSquaresSvg);
  registerIcon('grid-squares-add', gridSquaresAddSvg);
  registerIcon('hand', handSvg);
  registerIcon('harddrive', harddriveSvg);
  registerIcon('hash', hashSvg);
  registerIcon('heart', heartSvg);
  registerIcon('heart-rate', heartRateSvg);
  registerIcon('heart-remove', heartRemoveSvg);
  registerIcon('height', heightSvg);
  registerIcon('hierarchy', hierarchySvg);
  registerIcon('home', homeSvg);
  registerIcon('home-alt', homeAltSvg);
  registerIcon('home-check', homeCheckSvg);
  registerIcon('home-door', homeDoorSvg);
  registerIcon('import', importSvg);
  registerIcon('inbox', inboxSvg);
  registerIcon('inbox-alt', inboxAltSvg);
  registerIcon('info-circle', infoCircleSvg);
  registerIcon('iphone-landscape', iphoneLandscapeSvg);
  registerIcon('iphone-portrait', iphonePortraitSvg);
  registerIcon('jump-backward', jumpBackwardSvg);
  registerIcon('jump-forward', jumpForwardSvg);
  registerIcon('jump-left', jumpLeftSvg);
  registerIcon('jump-right', jumpRightSvg);
  registerIcon('keyboard', keyboardSvg);
  registerIcon('laptop', laptopSvg);
  registerIcon('lightbulb', lightbulbSvg);
  registerIcon('lightbulb-on', lightbulbOnSvg);
  registerIcon('lightning', lightningSvg);
  registerIcon('lightning-alt', lightningAltSvg);
  registerIcon('lineweight', lineweightSvg);
  registerIcon('link', linkSvg);
  registerIcon('link-alt', linkAltSvg);
  registerIcon('link-broken', linkBrokenSvg);
  registerIcon('link-horizontal', linkHorizontalSvg);
  registerIcon('link-vertical', linkVerticalSvg);
  registerIcon('list', listSvg);
  registerIcon('list-add', listAddSvg);
  registerIcon('list-numbered', listNumberedSvg);
  registerIcon('loader', loaderSvg);
  registerIcon('location', locationSvg);
  registerIcon('lock', lockSvg);
  registerIcon('lock-open', lockOpenSvg);
  registerIcon('mail', mailSvg);
  registerIcon('mail-add', mailAddSvg);
  registerIcon('mail-delete', mailDeleteSvg);
  registerIcon('mail-minus', mailMinusSvg);
  registerIcon('mail-new', mailNewSvg);
  registerIcon('mail-open', mailOpenSvg);
  registerIcon('mail-remove', mailRemoveSvg);
  registerIcon('marquee', marqueeSvg);
  registerIcon('maximise', maximiseSvg);
  registerIcon('menu-hamburger', menuHamburgerSvg);
  registerIcon('menu-horizontal', menuHorizontalSvg);
  registerIcon('menu-vertical', menuVerticalSvg);
  registerIcon('message', messageSvg);
  registerIcon('message-writing', messageWritingSvg);
  registerIcon('microphone', microphoneSvg);
  registerIcon('microphone-disabled', microphoneDisabledSvg);
  registerIcon('microphone-muted', microphoneMutedSvg);
  registerIcon('midpoint', midpointSvg);
  registerIcon('mini-player', miniPlayerSvg);
  registerIcon('minimise', minimiseSvg);
  registerIcon('minus', minusSvg);
  registerIcon('minus-circle', minusCircleSvg);
  registerIcon('moon', moonSvg);
  registerIcon('move', moveSvg);
  registerIcon('newspaper', newspaperSvg);
  registerIcon('no-sign', noSignSvg);
  registerIcon('notebook', notebookSvg);
  registerIcon('notification', notificationSvg);
  registerIcon('nut', nutSvg);
  registerIcon('pages', pagesSvg);
  registerIcon('panel-bottom', panelBottomSvg);
  registerIcon('panel-center', panelCenterSvg);
  registerIcon('panel-left', panelLeftSvg);
  registerIcon('panel-right', panelRightSvg);
  registerIcon('panel-sectioned', panelSectionedSvg);
  registerIcon('panel-top', panelTopSvg);
  registerIcon('paper', paperSvg);
  registerIcon('paper-folded', paperFoldedSvg);
  registerIcon('paper-plane', paperPlaneSvg);
  registerIcon('paper-plane-alt', paperPlaneAltSvg);
  registerIcon('paperclip', paperclipSvg);
  registerIcon('paragraph-center', paragraphCenterSvg);
  registerIcon('paragraph-end', paragraphEndSvg);
  registerIcon('paragraph-left', paragraphLeftSvg);
  registerIcon('paragraph-right', paragraphRightSvg);
  registerIcon('paragraph-start', paragraphStartSvg);
  registerIcon('pen', penSvg);
  registerIcon('phone-landscape', phoneLandscapeSvg);
  registerIcon('phone-portrait', phonePortraitSvg);
  registerIcon('picture', pictureSvg);
  registerIcon('pie-half', pieHalfSvg);
  registerIcon('pie-quarter', pieQuarterSvg);
  registerIcon('pie-third', pieThirdSvg);
  registerIcon('pill', pillSvg);
  registerIcon('play-button', playButtonSvg);
  registerIcon('plus', plusSvg);
  registerIcon('plus-circle', plusCircleSvg);
  registerIcon('postcard', postcardSvg);
  registerIcon('printer', printerSvg);
  registerIcon('projector', projectorSvg);
  registerIcon('pull-down', pullDownSvg);
  registerIcon('pull-left', pullLeftSvg);
  registerIcon('pull-right', pullRightSvg);
  registerIcon('pull-up', pullUpSvg);
  registerIcon('push-down', pushDownSvg);
  registerIcon('push-left', pushLeftSvg);
  registerIcon('push-right', pushRightSvg);
  registerIcon('push-up', pushUpSvg);
  registerIcon('question-circle', questionCircleSvg);
  registerIcon('radio-on', radioOnSvg);
  registerIcon('receipt', receiptSvg);
  registerIcon('record', recordSvg);
  registerIcon('redo', redoSvg);
  registerIcon('refresh', refreshSvg);
  registerIcon('refresh-alt', refreshAltSvg);
  registerIcon('replicate', replicateSvg);
  registerIcon('replicate-alt', replicateAltSvg);
  registerIcon('reset', resetSvg);
  registerIcon('reset-alt', resetAltSvg);
  registerIcon('reset-forward', resetForwardSvg);
  registerIcon('reset-hard', resetHardSvg);
  registerIcon('reset-temporary', resetTemporarySvg);
  registerIcon('retweet', retweetSvg);
  registerIcon('reuse', reuseSvg);
  registerIcon('reverse', reverseSvg);
  registerIcon('reverse-alt', reverseAltSvg);
  registerIcon('revert', revertSvg);
  registerIcon('rocket', rocketSvg);
  registerIcon('ruler', rulerSvg);
  registerIcon('scale', scaleSvg);
  registerIcon('scale-contract', scaleContractSvg);
  registerIcon('scale-extend', scaleExtendSvg);
  registerIcon('scalpel', scalpelSvg);
  registerIcon('search', searchSvg);
  registerIcon('server', serverSvg);
  registerIcon('settings', settingsSvg);
  registerIcon('share', shareSvg);
  registerIcon('share-alt', shareAltSvg);
  registerIcon('shuffle', shuffleSvg);
  registerIcon('side-menu', sideMenuSvg);
  registerIcon('signal-full', signalFullSvg);
  registerIcon('signal-low', signalLowSvg);
  registerIcon('signal-medium', signalMediumSvg);
  registerIcon('signal-none', signalNoneSvg);
  registerIcon('slash-backward', slashBackwardSvg);
  registerIcon('slash-forward', slashForwardSvg);
  registerIcon('sliders', slidersSvg);
  registerIcon('sort', sortSvg);
  registerIcon('sort-alt', sortAltSvg);
  registerIcon('speaker', speakerSvg);
  registerIcon('speech-bubble', speechBubbleSvg);
  registerIcon('speech-typing', speechTypingSvg);
  registerIcon('split', splitSvg);
  registerIcon('split-three', splitThreeSvg);
  registerIcon('star', starSvg);
  registerIcon('sun', sunSvg);
  registerIcon('support', supportSvg);
  registerIcon('swap', swapSvg);
  registerIcon('switch', switchSvg);
  registerIcon('table', tableSvg);
  registerIcon('table-header', tableHeaderSvg);
  registerIcon('tag', tagSvg);
  registerIcon('tag-milestone', tagMilestoneSvg);
  registerIcon('tags', tagsSvg);
  registerIcon('target', targetSvg);
  registerIcon('terminal', terminalSvg);
  registerIcon('thread', threadSvg);
  registerIcon('thumbs-down', thumbsDownSvg);
  registerIcon('thumbs-up', thumbsUpSvg);
  registerIcon('ticket', ticketSvg);
  registerIcon('timeline', timelineSvg);
  registerIcon('todo', todoSvg);
  registerIcon('toggle', toggleSvg);
  registerIcon('toggles', togglesSvg);
  registerIcon('translate', translateSvg);
  registerIcon('trash', trashSvg);
  registerIcon('trash-alt', trashAltSvg);
  registerIcon('trophy', trophySvg);
  registerIcon('tv-mode', tvModeSvg);
  registerIcon('unarchive', unarchiveSvg);
  registerIcon('undo', undoSvg);
  registerIcon('undo-history', undoHistorySvg);
  registerIcon('unlink-horizontal', unlinkHorizontalSvg);
  registerIcon('unlink-vertical', unlinkVerticalSvg);
  registerIcon('upload', uploadSvg);
  registerIcon('upload-alt', uploadAltSvg);
  registerIcon('upward', upwardSvg);
  registerIcon('user', userSvg);
  registerIcon('user-add', userAddSvg);
  registerIcon('user-circle', userCircleSvg);
  registerIcon('user-male', userMaleSvg);
  registerIcon('user-male-circle', userMaleCircleSvg);
  registerIcon('user-remove', userRemoveSvg);
  registerIcon('users', usersSvg);
  registerIcon('venn', vennSvg);
  registerIcon('version', versionSvg);
  registerIcon('versions', versionsSvg);
  registerIcon('video', videoSvg);
  registerIcon('volume-0', volume0Svg);
  registerIcon('volume-add', volumeAddSvg);
  registerIcon('volume-disabled', volumeDisabledSvg);
  registerIcon('volume-high', volumeHighSvg);
  registerIcon('volume-low', volumeLowSvg);
  registerIcon('volume-minus', volumeMinusSvg);
  registerIcon('volume-muted', volumeMutedSvg);
  registerIcon('wallet', walletSvg);
  registerIcon('warning-circle', warningCircleSvg);
  registerIcon('warning-hex', warningHexSvg);
  registerIcon('warning-triangle', warningTriangleSvg);
  registerIcon('waves', wavesSvg);
  registerIcon('width', widthSvg);
  registerIcon('wifi', wifiSvg);
  registerIcon('wifi-error', wifiErrorSvg);
  registerIcon('wifi-none', wifiNoneSvg);
  registerIcon('window', windowSvg);
  registerIcon('window-collapse-left', windowCollapseLeftSvg);
  registerIcon('window-collapse-right', windowCollapseRightSvg);
  registerIcon('window-content', windowContentSvg);
  registerIcon('wrap-back', wrapBackSvg);
  registerIcon('wrap-forward', wrapForwardSvg);
  registerIcon('write', writeSvg);
  registerIcon('zoom-cancel', zoomCancelSvg);
  registerIcon('zoom-in', zoomInSvg);
  registerIcon('zoom-out', zoomOutSvg);
  registerIcon('zoom-reset', zoomResetSvg);
