/**
 * Auto-generated icon registry from System UI Icons
 * Generated: 2026-01-01T04:23:26.978Z
 * Total icons: 430
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: node source/components/icon/generate-icon-registry.js
 */

import { html, type TemplateResult } from 'lit';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';

import airplay from '../../../assets/icons/airplay.svg?raw';
import alarm_clock from '../../../assets/icons/alarm_clock.svg?raw';
import align_horizontal from '../../../assets/icons/align_horizontal.svg?raw';
import align_vertical from '../../../assets/icons/align_vertical.svg?raw';
import angle from '../../../assets/icons/angle.svg?raw';
import archive from '../../../assets/icons/archive.svg?raw';
import arrow_bottom_left from '../../../assets/icons/arrow_bottom_left.svg?raw';
import arrow_bottom_right from '../../../assets/icons/arrow_bottom_right.svg?raw';
import arrow_down from '../../../assets/icons/arrow_down.svg?raw';
import arrow_down_circle from '../../../assets/icons/arrow_down_circle.svg?raw';
import arrow_left from '../../../assets/icons/arrow_left.svg?raw';
import arrow_left_circle from '../../../assets/icons/arrow_left_circle.svg?raw';
import arrow_right from '../../../assets/icons/arrow_right.svg?raw';
import arrow_right_circle from '../../../assets/icons/arrow_right_circle.svg?raw';
import arrow_top_left from '../../../assets/icons/arrow_top_left.svg?raw';
import arrow_top_right from '../../../assets/icons/arrow_top_right.svg?raw';
import arrow_up from '../../../assets/icons/arrow_up.svg?raw';
import arrow_up_circle from '../../../assets/icons/arrow_up_circle.svg?raw';
import audio_wave from '../../../assets/icons/audio_wave.svg?raw';
import backspace from '../../../assets/icons/backspace.svg?raw';
import backward from '../../../assets/icons/backward.svg?raw';
import bag from '../../../assets/icons/bag.svg?raw';
import battery_75 from '../../../assets/icons/battery_75.svg?raw';
import battery_charging from '../../../assets/icons/battery_charging.svg?raw';
import battery_empty from '../../../assets/icons/battery_empty.svg?raw';
import battery_full from '../../../assets/icons/battery_full.svg?raw';
import battery_half from '../../../assets/icons/battery_half.svg?raw';
import battery_low from '../../../assets/icons/battery_low.svg?raw';
import bell from '../../../assets/icons/bell.svg?raw';
import bell_disabled from '../../../assets/icons/bell_disabled.svg?raw';
import bell_ringing from '../../../assets/icons/bell_ringing.svg?raw';
import bell_snooze from '../../../assets/icons/bell_snooze.svg?raw';
import bluetooth from '../../../assets/icons/bluetooth.svg?raw';
import book from '../../../assets/icons/book.svg?raw';
import book_closed from '../../../assets/icons/book_closed.svg?raw';
import book_text from '../../../assets/icons/book_text.svg?raw';
import bookmark from '../../../assets/icons/bookmark.svg?raw';
import bookmark_book from '../../../assets/icons/bookmark_book.svg?raw';
import box from '../../../assets/icons/box.svg?raw';
import box_add from '../../../assets/icons/box_add.svg?raw';
import box_download from '../../../assets/icons/box_download.svg?raw';
import box_open from '../../../assets/icons/box_open.svg?raw';
import box_remove from '../../../assets/icons/box_remove.svg?raw';
import boxes from '../../../assets/icons/boxes.svg?raw';
import branch from '../../../assets/icons/branch.svg?raw';
import briefcase from '../../../assets/icons/briefcase.svg?raw';
import browser from '../../../assets/icons/browser.svg?raw';
import browser_alt from '../../../assets/icons/browser_alt.svg?raw';
import button_add from '../../../assets/icons/button_add.svg?raw';
import button_minus from '../../../assets/icons/button_minus.svg?raw';
import calculator from '../../../assets/icons/calculator.svg?raw';
import calendar from '../../../assets/icons/calendar.svg?raw';
import calendar_add from '../../../assets/icons/calendar_add.svg?raw';
import calendar_date from '../../../assets/icons/calendar_date.svg?raw';
import calendar_day from '../../../assets/icons/calendar_day.svg?raw';
import calendar_days from '../../../assets/icons/calendar_days.svg?raw';
import calendar_last_day from '../../../assets/icons/calendar_last_day.svg?raw';
import calendar_month from '../../../assets/icons/calendar_month.svg?raw';
import calendar_move from '../../../assets/icons/calendar_move.svg?raw';
import calendar_remove from '../../../assets/icons/calendar_remove.svg?raw';
import calendar_split from '../../../assets/icons/calendar_split.svg?raw';
import calendar_week from '../../../assets/icons/calendar_week.svg?raw';
import camera from '../../../assets/icons/camera.svg?raw';
import camera_alt from '../../../assets/icons/camera_alt.svg?raw';
import camera_noflash from '../../../assets/icons/camera_noflash.svg?raw';
import camera_noflash_alt from '../../../assets/icons/camera_noflash_alt.svg?raw';
import capture from '../../../assets/icons/capture.svg?raw';
import card_timeline from '../../../assets/icons/card_timeline.svg?raw';
import card_view from '../../../assets/icons/card_view.svg?raw';
import carousel from '../../../assets/icons/carousel.svg?raw';
import cart from '../../../assets/icons/cart.svg?raw';
import cast from '../../../assets/icons/cast.svg?raw';
import chain from '../../../assets/icons/chain.svg?raw';
import chat_add from '../../../assets/icons/chat_add.svg?raw';
import check from '../../../assets/icons/check.svg?raw';
import check_circle from '../../../assets/icons/check_circle.svg?raw';
import check_circle_outside from '../../../assets/icons/check_circle_outside.svg?raw';
import checkbox_checked from '../../../assets/icons/checkbox_checked.svg?raw';
import checkbox_empty from '../../../assets/icons/checkbox_empty.svg?raw';
import chevron_close from '../../../assets/icons/chevron_close.svg?raw';
import chevron_down from '../../../assets/icons/chevron_down.svg?raw';
import chevron_down_circle from '../../../assets/icons/chevron_down_circle.svg?raw';
import chevron_down_double from '../../../assets/icons/chevron_down_double.svg?raw';
import chevron_left from '../../../assets/icons/chevron_left.svg?raw';
import chevron_left_circle from '../../../assets/icons/chevron_left_circle.svg?raw';
import chevron_left_double from '../../../assets/icons/chevron_left_double.svg?raw';
import chevron_open from '../../../assets/icons/chevron_open.svg?raw';
import chevron_right from '../../../assets/icons/chevron_right.svg?raw';
import chevron_right_circle from '../../../assets/icons/chevron_right_circle.svg?raw';
import chevron_right_double from '../../../assets/icons/chevron_right_double.svg?raw';
import chevron_up from '../../../assets/icons/chevron_up.svg?raw';
import chevron_up_circle from '../../../assets/icons/chevron_up_circle.svg?raw';
import chevron_up_double from '../../../assets/icons/chevron_up_double.svg?raw';
import circle from '../../../assets/icons/circle.svg?raw';
import circle_menu from '../../../assets/icons/circle_menu.svg?raw';
import circle_split from '../../../assets/icons/circle_split.svg?raw';
import clipboard from '../../../assets/icons/clipboard.svg?raw';
import clipboard_add from '../../../assets/icons/clipboard_add.svg?raw';
import clipboard_check from '../../../assets/icons/clipboard_check.svg?raw';
import clipboard_copy from '../../../assets/icons/clipboard_copy.svg?raw';
import clipboard_cross from '../../../assets/icons/clipboard_cross.svg?raw';
import clipboard_notes from '../../../assets/icons/clipboard_notes.svg?raw';
import clipboard_remove from '../../../assets/icons/clipboard_remove.svg?raw';
import clock from '../../../assets/icons/clock.svg?raw';
import close from '../../../assets/icons/close.svg?raw';
import cloud from '../../../assets/icons/cloud.svg?raw';
import cloud_disconnect from '../../../assets/icons/cloud_disconnect.svg?raw';
import cloud_download from '../../../assets/icons/cloud_download.svg?raw';
import cloud_download_alt from '../../../assets/icons/cloud_download_alt.svg?raw';
import cloud_upload from '../../../assets/icons/cloud_upload.svg?raw';
import cloud_upload_alt from '../../../assets/icons/cloud_upload_alt.svg?raw';
import code from '../../../assets/icons/code.svg?raw';
import coffee from '../../../assets/icons/coffee.svg?raw';
import coin from '../../../assets/icons/coin.svg?raw';
import coins from '../../../assets/icons/coins.svg?raw';
import compass from '../../../assets/icons/compass.svg?raw';
import component_add from '../../../assets/icons/component_add.svg?raw';
import contacts from '../../../assets/icons/contacts.svg?raw';
import contract from '../../../assets/icons/contract.svg?raw';
import create from '../../../assets/icons/create.svg?raw';
import credit_card from '../../../assets/icons/credit_card.svg?raw';
import crop from '../../../assets/icons/crop.svg?raw';
import cross from '../../../assets/icons/cross.svg?raw';
import cross_circle from '../../../assets/icons/cross_circle.svg?raw';
import crosshair from '../../../assets/icons/crosshair.svg?raw';
import cube from '../../../assets/icons/cube.svg?raw';
import cubes from '../../../assets/icons/cubes.svg?raw';
import cylinder from '../../../assets/icons/cylinder.svg?raw';
import database from '../../../assets/icons/database.svg?raw';
import diamond from '../../../assets/icons/diamond.svg?raw';
import directions from '../../../assets/icons/directions.svg?raw';
import disc from '../../../assets/icons/disc.svg?raw';
import display from '../../../assets/icons/display.svg?raw';
import display_alt from '../../../assets/icons/display_alt.svg?raw';
import document from '../../../assets/icons/document.svg?raw';
import document_justified from '../../../assets/icons/document_justified.svg?raw';
import document_list from '../../../assets/icons/document_list.svg?raw';
import document_stack from '../../../assets/icons/document_stack.svg?raw';
import document_words from '../../../assets/icons/document_words.svg?raw';
import door from '../../../assets/icons/door.svg?raw';
import door_alt from '../../../assets/icons/door_alt.svg?raw';
import download from '../../../assets/icons/download.svg?raw';
import download_alt from '../../../assets/icons/download_alt.svg?raw';
import downward from '../../../assets/icons/downward.svg?raw';
import drag from '../../../assets/icons/drag.svg?raw';
import drag_circle from '../../../assets/icons/drag_circle.svg?raw';
import drag_vertical from '../../../assets/icons/drag_vertical.svg?raw';
import duplicate from '../../../assets/icons/duplicate.svg?raw';
import duplicate_alt from '../../../assets/icons/duplicate_alt.svg?raw';
import enter from '../../../assets/icons/enter.svg?raw';
import enter_alt from '../../../assets/icons/enter_alt.svg?raw';
import episodes from '../../../assets/icons/episodes.svg?raw';
import exit_left from '../../../assets/icons/exit_left.svg?raw';
import exit_right from '../../../assets/icons/exit_right.svg?raw';
import expand from '../../../assets/icons/expand.svg?raw';
import expand_height from '../../../assets/icons/expand_height.svg?raw';
import expand_width from '../../../assets/icons/expand_width.svg?raw';
import external from '../../../assets/icons/external.svg?raw';
import eye from '../../../assets/icons/eye.svg?raw';
import eye_closed from '../../../assets/icons/eye_closed.svg?raw';
import eye_no from '../../../assets/icons/eye_no.svg?raw';
import face_delighted from '../../../assets/icons/face_delighted.svg?raw';
import face_happy from '../../../assets/icons/face_happy.svg?raw';
import face_neutral from '../../../assets/icons/face_neutral.svg?raw';
import face_sad from '../../../assets/icons/face_sad.svg?raw';
import file_download from '../../../assets/icons/file_download.svg?raw';
import file_upload from '../../../assets/icons/file_upload.svg?raw';
import files_history from '../../../assets/icons/files_history.svg?raw';
import files_multi from '../../../assets/icons/files_multi.svg?raw';
import files_stack from '../../../assets/icons/files_stack.svg?raw';
import film from '../../../assets/icons/film.svg?raw';
import filter from '../../../assets/icons/filter.svg?raw';
import filter_circle from '../../../assets/icons/filter_circle.svg?raw';
import filter_single from '../../../assets/icons/filter_single.svg?raw';
import filtering from '../../../assets/icons/filtering.svg?raw';
import fingerprint from '../../../assets/icons/fingerprint.svg?raw';
import flag from '../../../assets/icons/flag.svg?raw';
import flame from '../../../assets/icons/flame.svg?raw';
import flame_alt from '../../../assets/icons/flame_alt.svg?raw';
import flip_view from '../../../assets/icons/flip_view.svg?raw';
import floppy from '../../../assets/icons/floppy.svg?raw';
import folder_add from '../../../assets/icons/folder_add.svg?raw';
import folder_closed from '../../../assets/icons/folder_closed.svg?raw';
import folder_minus from '../../../assets/icons/folder_minus.svg?raw';
import folder_open from '../../../assets/icons/folder_open.svg?raw';
import fork_git from '../../../assets/icons/fork_git.svg?raw';
import forward from '../../../assets/icons/forward.svg?raw';
import frame from '../../../assets/icons/frame.svg?raw';
import fullscreen from '../../../assets/icons/fullscreen.svg?raw';
import funnel from '../../../assets/icons/funnel.svg?raw';
import gauge from '../../../assets/icons/gauge.svg?raw';
import gift from '../../../assets/icons/gift.svg?raw';
import globe from '../../../assets/icons/globe.svg?raw';
import gps from '../../../assets/icons/gps.svg?raw';
import grab from '../../../assets/icons/grab.svg?raw';
import graph_bar from '../../../assets/icons/graph_bar.svg?raw';
import graph_box from '../../../assets/icons/graph_box.svg?raw';
import graph_increase from '../../../assets/icons/graph_increase.svg?raw';
import grid from '../../../assets/icons/grid.svg?raw';
import grid_circles from '../../../assets/icons/grid_circles.svg?raw';
import grid_circles_add from '../../../assets/icons/grid_circles_add.svg?raw';
import grid_small from '../../../assets/icons/grid_small.svg?raw';
import grid_squares from '../../../assets/icons/grid_squares.svg?raw';
import grid_squares_add from '../../../assets/icons/grid_squares_add.svg?raw';
import hand from '../../../assets/icons/hand.svg?raw';
import harddrive from '../../../assets/icons/harddrive.svg?raw';
import hash from '../../../assets/icons/hash.svg?raw';
import heart from '../../../assets/icons/heart.svg?raw';
import heart_rate from '../../../assets/icons/heart_rate.svg?raw';
import heart_remove from '../../../assets/icons/heart_remove.svg?raw';
import height from '../../../assets/icons/height.svg?raw';
import hierarchy from '../../../assets/icons/hierarchy.svg?raw';
import home from '../../../assets/icons/home.svg?raw';
import home_alt from '../../../assets/icons/home_alt.svg?raw';
import home_check from '../../../assets/icons/home_check.svg?raw';
import home_door from '../../../assets/icons/home_door.svg?raw';
import _import from '../../../assets/icons/import.svg?raw';
import inbox from '../../../assets/icons/inbox.svg?raw';
import inbox_alt from '../../../assets/icons/inbox_alt.svg?raw';
import info_circle from '../../../assets/icons/info_circle.svg?raw';
import iphone_landscape from '../../../assets/icons/iphone_landscape.svg?raw';
import iphone_portrait from '../../../assets/icons/iphone_portrait.svg?raw';
import jump_backward from '../../../assets/icons/jump_backward.svg?raw';
import jump_forward from '../../../assets/icons/jump_forward.svg?raw';
import jump_left from '../../../assets/icons/jump_left.svg?raw';
import jump_right from '../../../assets/icons/jump_right.svg?raw';
import keyboard from '../../../assets/icons/keyboard.svg?raw';
import laptop from '../../../assets/icons/laptop.svg?raw';
import lightbulb from '../../../assets/icons/lightbulb.svg?raw';
import lightbulb_on from '../../../assets/icons/lightbulb_on.svg?raw';
import lightning from '../../../assets/icons/lightning.svg?raw';
import lightning_alt from '../../../assets/icons/lightning_alt.svg?raw';
import lineweight from '../../../assets/icons/lineweight.svg?raw';
import link from '../../../assets/icons/link.svg?raw';
import link_alt from '../../../assets/icons/link_alt.svg?raw';
import link_broken from '../../../assets/icons/link_broken.svg?raw';
import link_horizontal from '../../../assets/icons/link_horizontal.svg?raw';
import link_vertical from '../../../assets/icons/link_vertical.svg?raw';
import list from '../../../assets/icons/list.svg?raw';
import list_add from '../../../assets/icons/list_add.svg?raw';
import list_numbered from '../../../assets/icons/list_numbered.svg?raw';
import loader from '../../../assets/icons/loader.svg?raw';
import location from '../../../assets/icons/location.svg?raw';
import lock from '../../../assets/icons/lock.svg?raw';
import lock_open from '../../../assets/icons/lock_open.svg?raw';
import mail from '../../../assets/icons/mail.svg?raw';
import mail_add from '../../../assets/icons/mail_add.svg?raw';
import mail_delete from '../../../assets/icons/mail_delete.svg?raw';
import mail_minus from '../../../assets/icons/mail_minus.svg?raw';
import mail_new from '../../../assets/icons/mail_new.svg?raw';
import mail_open from '../../../assets/icons/mail_open.svg?raw';
import mail_remove from '../../../assets/icons/mail_remove.svg?raw';
import marquee from '../../../assets/icons/marquee.svg?raw';
import maximise from '../../../assets/icons/maximise.svg?raw';
import menu_hamburger from '../../../assets/icons/menu_hamburger.svg?raw';
import menu_horizontal from '../../../assets/icons/menu_horizontal.svg?raw';
import menu_vertical from '../../../assets/icons/menu_vertical.svg?raw';
import message from '../../../assets/icons/message.svg?raw';
import message_writing from '../../../assets/icons/message_writing.svg?raw';
import microphone from '../../../assets/icons/microphone.svg?raw';
import microphone_disabled from '../../../assets/icons/microphone_disabled.svg?raw';
import microphone_muted from '../../../assets/icons/microphone_muted.svg?raw';
import midpoint from '../../../assets/icons/midpoint.svg?raw';
import mini_player from '../../../assets/icons/mini_player.svg?raw';
import minimise from '../../../assets/icons/minimise.svg?raw';
import minus from '../../../assets/icons/minus.svg?raw';
import minus_circle from '../../../assets/icons/minus_circle.svg?raw';
import moon from '../../../assets/icons/moon.svg?raw';
import move from '../../../assets/icons/move.svg?raw';
import newspaper from '../../../assets/icons/newspaper.svg?raw';
import no_sign from '../../../assets/icons/no_sign.svg?raw';
import notebook from '../../../assets/icons/notebook.svg?raw';
import notification from '../../../assets/icons/notification.svg?raw';
import nut from '../../../assets/icons/nut.svg?raw';
import pages from '../../../assets/icons/pages.svg?raw';
import panel_bottom from '../../../assets/icons/panel_bottom.svg?raw';
import panel_center from '../../../assets/icons/panel_center.svg?raw';
import panel_left from '../../../assets/icons/panel_left.svg?raw';
import panel_right from '../../../assets/icons/panel_right.svg?raw';
import panel_sectioned from '../../../assets/icons/panel_sectioned.svg?raw';
import panel_top from '../../../assets/icons/panel_top.svg?raw';
import paper from '../../../assets/icons/paper.svg?raw';
import paper_folded from '../../../assets/icons/paper_folded.svg?raw';
import paper_plane from '../../../assets/icons/paper_plane.svg?raw';
import paper_plane_alt from '../../../assets/icons/paper_plane_alt.svg?raw';
import paperclip from '../../../assets/icons/paperclip.svg?raw';
import paragraph_center from '../../../assets/icons/paragraph_center.svg?raw';
import paragraph_end from '../../../assets/icons/paragraph_end.svg?raw';
import paragraph_left from '../../../assets/icons/paragraph_left.svg?raw';
import paragraph_right from '../../../assets/icons/paragraph_right.svg?raw';
import paragraph_start from '../../../assets/icons/paragraph_start.svg?raw';
import pen from '../../../assets/icons/pen.svg?raw';
import phone_landscape from '../../../assets/icons/phone_landscape.svg?raw';
import phone_portrait from '../../../assets/icons/phone_portrait.svg?raw';
import picture from '../../../assets/icons/picture.svg?raw';
import pie_half from '../../../assets/icons/pie_half.svg?raw';
import pie_quarter from '../../../assets/icons/pie_quarter.svg?raw';
import pie_third from '../../../assets/icons/pie_third.svg?raw';
import pill from '../../../assets/icons/pill.svg?raw';
import play_button from '../../../assets/icons/play_button.svg?raw';
import plus from '../../../assets/icons/plus.svg?raw';
import plus_circle from '../../../assets/icons/plus_circle.svg?raw';
import postcard from '../../../assets/icons/postcard.svg?raw';
import printer from '../../../assets/icons/printer.svg?raw';
import projector from '../../../assets/icons/projector.svg?raw';
import pull_down from '../../../assets/icons/pull_down.svg?raw';
import pull_left from '../../../assets/icons/pull_left.svg?raw';
import pull_right from '../../../assets/icons/pull_right.svg?raw';
import pull_up from '../../../assets/icons/pull_up.svg?raw';
import push_down from '../../../assets/icons/push_down.svg?raw';
import push_left from '../../../assets/icons/push_left.svg?raw';
import push_right from '../../../assets/icons/push_right.svg?raw';
import push_up from '../../../assets/icons/push_up.svg?raw';
import question_circle from '../../../assets/icons/question_circle.svg?raw';
import radio_on from '../../../assets/icons/radio_on.svg?raw';
import receipt from '../../../assets/icons/receipt.svg?raw';
import record from '../../../assets/icons/record.svg?raw';
import redo from '../../../assets/icons/redo.svg?raw';
import refresh from '../../../assets/icons/refresh.svg?raw';
import refresh_alt from '../../../assets/icons/refresh_alt.svg?raw';
import replicate from '../../../assets/icons/replicate.svg?raw';
import replicate_alt from '../../../assets/icons/replicate_alt.svg?raw';
import reset from '../../../assets/icons/reset.svg?raw';
import reset_alt from '../../../assets/icons/reset_alt.svg?raw';
import reset_forward from '../../../assets/icons/reset_forward.svg?raw';
import reset_hard from '../../../assets/icons/reset_hard.svg?raw';
import reset_temporary from '../../../assets/icons/reset_temporary.svg?raw';
import retweet from '../../../assets/icons/retweet.svg?raw';
import reuse from '../../../assets/icons/reuse.svg?raw';
import reverse from '../../../assets/icons/reverse.svg?raw';
import reverse_alt from '../../../assets/icons/reverse_alt.svg?raw';
import revert from '../../../assets/icons/revert.svg?raw';
import rocket from '../../../assets/icons/rocket.svg?raw';
import ruler from '../../../assets/icons/ruler.svg?raw';
import scale from '../../../assets/icons/scale.svg?raw';
import scale_contract from '../../../assets/icons/scale_contract.svg?raw';
import scale_extend from '../../../assets/icons/scale_extend.svg?raw';
import scalpel from '../../../assets/icons/scalpel.svg?raw';
import search from '../../../assets/icons/search.svg?raw';
import server from '../../../assets/icons/server.svg?raw';
import settings from '../../../assets/icons/settings.svg?raw';
import share from '../../../assets/icons/share.svg?raw';
import share_alt from '../../../assets/icons/share_alt.svg?raw';
import shuffle from '../../../assets/icons/shuffle.svg?raw';
import side_menu from '../../../assets/icons/side_menu.svg?raw';
import signal_full from '../../../assets/icons/signal_full.svg?raw';
import signal_low from '../../../assets/icons/signal_low.svg?raw';
import signal_medium from '../../../assets/icons/signal_medium.svg?raw';
import signal_none from '../../../assets/icons/signal_none.svg?raw';
import slash_backward from '../../../assets/icons/slash_backward.svg?raw';
import slash_forward from '../../../assets/icons/slash_forward.svg?raw';
import sliders from '../../../assets/icons/sliders.svg?raw';
import sort from '../../../assets/icons/sort.svg?raw';
import sort_alt from '../../../assets/icons/sort_alt.svg?raw';
import speaker from '../../../assets/icons/speaker.svg?raw';
import speech_bubble from '../../../assets/icons/speech_bubble.svg?raw';
import speech_typing from '../../../assets/icons/speech_typing.svg?raw';
import split from '../../../assets/icons/split.svg?raw';
import split_three from '../../../assets/icons/split_three.svg?raw';
import star from '../../../assets/icons/star.svg?raw';
import sun from '../../../assets/icons/sun.svg?raw';
import support from '../../../assets/icons/support.svg?raw';
import swap from '../../../assets/icons/swap.svg?raw';
import _switch from '../../../assets/icons/switch.svg?raw';
import table from '../../../assets/icons/table.svg?raw';
import table_header from '../../../assets/icons/table_header.svg?raw';
import tag from '../../../assets/icons/tag.svg?raw';
import tag_milestone from '../../../assets/icons/tag_milestone.svg?raw';
import tags from '../../../assets/icons/tags.svg?raw';
import target from '../../../assets/icons/target.svg?raw';
import terminal from '../../../assets/icons/terminal.svg?raw';
import thread from '../../../assets/icons/thread.svg?raw';
import thumbs_down from '../../../assets/icons/thumbs_down.svg?raw';
import thumbs_up from '../../../assets/icons/thumbs_up.svg?raw';
import ticket from '../../../assets/icons/ticket.svg?raw';
import timeline from '../../../assets/icons/timeline.svg?raw';
import todo from '../../../assets/icons/todo.svg?raw';
import toggle from '../../../assets/icons/toggle.svg?raw';
import toggles from '../../../assets/icons/toggles.svg?raw';
import translate from '../../../assets/icons/translate.svg?raw';
import trash from '../../../assets/icons/trash.svg?raw';
import trash_alt from '../../../assets/icons/trash_alt.svg?raw';
import trophy from '../../../assets/icons/trophy.svg?raw';
import tv_mode from '../../../assets/icons/tv_mode.svg?raw';
import unarchive from '../../../assets/icons/unarchive.svg?raw';
import undo from '../../../assets/icons/undo.svg?raw';
import undo_history from '../../../assets/icons/undo_history.svg?raw';
import unlink_horizontal from '../../../assets/icons/unlink_horizontal.svg?raw';
import unlink_vertical from '../../../assets/icons/unlink_vertical.svg?raw';
import upload from '../../../assets/icons/upload.svg?raw';
import upload_alt from '../../../assets/icons/upload_alt.svg?raw';
import upward from '../../../assets/icons/upward.svg?raw';
import user from '../../../assets/icons/user.svg?raw';
import user_add from '../../../assets/icons/user_add.svg?raw';
import user_circle from '../../../assets/icons/user_circle.svg?raw';
import user_male from '../../../assets/icons/user_male.svg?raw';
import user_male_circle from '../../../assets/icons/user_male_circle.svg?raw';
import user_remove from '../../../assets/icons/user_remove.svg?raw';
import users from '../../../assets/icons/users.svg?raw';
import venn from '../../../assets/icons/venn.svg?raw';
import version from '../../../assets/icons/version.svg?raw';
import versions from '../../../assets/icons/versions.svg?raw';
import video from '../../../assets/icons/video.svg?raw';
import volume_0 from '../../../assets/icons/volume_0.svg?raw';
import volume_add from '../../../assets/icons/volume_add.svg?raw';
import volume_disabled from '../../../assets/icons/volume_disabled.svg?raw';
import volume_high from '../../../assets/icons/volume_high.svg?raw';
import volume_low from '../../../assets/icons/volume_low.svg?raw';
import volume_minus from '../../../assets/icons/volume_minus.svg?raw';
import volume_muted from '../../../assets/icons/volume_muted.svg?raw';
import wallet from '../../../assets/icons/wallet.svg?raw';
import warning_circle from '../../../assets/icons/warning_circle.svg?raw';
import warning_hex from '../../../assets/icons/warning_hex.svg?raw';
import warning_triangle from '../../../assets/icons/warning_triangle.svg?raw';
import waves from '../../../assets/icons/waves.svg?raw';
import width from '../../../assets/icons/width.svg?raw';
import wifi from '../../../assets/icons/wifi.svg?raw';
import wifi_error from '../../../assets/icons/wifi_error.svg?raw';
import wifi_none from '../../../assets/icons/wifi_none.svg?raw';
import window from '../../../assets/icons/window.svg?raw';
import window_collapse_left from '../../../assets/icons/window_collapse_left.svg?raw';
import window_collapse_right from '../../../assets/icons/window_collapse_right.svg?raw';
import window_content from '../../../assets/icons/window_content.svg?raw';
import wrap_back from '../../../assets/icons/wrap_back.svg?raw';
import wrap_forward from '../../../assets/icons/wrap_forward.svg?raw';
import write from '../../../assets/icons/write.svg?raw';
import zoom_cancel from '../../../assets/icons/zoom_cancel.svg?raw';
import zoom_in from '../../../assets/icons/zoom_in.svg?raw';
import zoom_out from '../../../assets/icons/zoom_out.svg?raw';
import zoom_reset from '../../../assets/icons/zoom_reset.svg?raw';

/**
 * Registry of all available System UI Icons
 */
const iconRegistry: Record<string, string> = {
  airplay: airplay,
  'alarm-clock': alarm_clock,
  'align-horizontal': align_horizontal,
  'align-vertical': align_vertical,
  angle: angle,
  archive: archive,
  'arrow-bottom-left': arrow_bottom_left,
  'arrow-bottom-right': arrow_bottom_right,
  'arrow-down': arrow_down,
  'arrow-down-circle': arrow_down_circle,
  'arrow-left': arrow_left,
  'arrow-left-circle': arrow_left_circle,
  'arrow-right': arrow_right,
  'arrow-right-circle': arrow_right_circle,
  'arrow-top-left': arrow_top_left,
  'arrow-top-right': arrow_top_right,
  'arrow-up': arrow_up,
  'arrow-up-circle': arrow_up_circle,
  'audio-wave': audio_wave,
  backspace: backspace,
  backward: backward,
  bag: bag,
  'battery-75': battery_75,
  'battery-charging': battery_charging,
  'battery-empty': battery_empty,
  'battery-full': battery_full,
  'battery-half': battery_half,
  'battery-low': battery_low,
  bell: bell,
  'bell-disabled': bell_disabled,
  'bell-ringing': bell_ringing,
  'bell-snooze': bell_snooze,
  bluetooth: bluetooth,
  book: book,
  'book-closed': book_closed,
  'book-text': book_text,
  bookmark: bookmark,
  'bookmark-book': bookmark_book,
  box: box,
  'box-add': box_add,
  'box-download': box_download,
  'box-open': box_open,
  'box-remove': box_remove,
  boxes: boxes,
  branch: branch,
  briefcase: briefcase,
  browser: browser,
  'browser-alt': browser_alt,
  'button-add': button_add,
  'button-minus': button_minus,
  calculator: calculator,
  calendar: calendar,
  'calendar-add': calendar_add,
  'calendar-date': calendar_date,
  'calendar-day': calendar_day,
  'calendar-days': calendar_days,
  'calendar-last-day': calendar_last_day,
  'calendar-month': calendar_month,
  'calendar-move': calendar_move,
  'calendar-remove': calendar_remove,
  'calendar-split': calendar_split,
  'calendar-week': calendar_week,
  camera: camera,
  'camera-alt': camera_alt,
  'camera-noflash': camera_noflash,
  'camera-noflash-alt': camera_noflash_alt,
  capture: capture,
  'card-timeline': card_timeline,
  'card-view': card_view,
  carousel: carousel,
  cart: cart,
  cast: cast,
  chain: chain,
  'chat-add': chat_add,
  check: check,
  'check-circle': check_circle,
  'check-circle-outside': check_circle_outside,
  'checkbox-checked': checkbox_checked,
  'checkbox-empty': checkbox_empty,
  'chevron-close': chevron_close,
  'chevron-down': chevron_down,
  'chevron-down-circle': chevron_down_circle,
  'chevron-down-double': chevron_down_double,
  'chevron-left': chevron_left,
  'chevron-left-circle': chevron_left_circle,
  'chevron-left-double': chevron_left_double,
  'chevron-open': chevron_open,
  'chevron-right': chevron_right,
  'chevron-right-circle': chevron_right_circle,
  'chevron-right-double': chevron_right_double,
  'chevron-up': chevron_up,
  'chevron-up-circle': chevron_up_circle,
  'chevron-up-double': chevron_up_double,
  circle: circle,
  'circle-menu': circle_menu,
  'circle-split': circle_split,
  clipboard: clipboard,
  'clipboard-add': clipboard_add,
  'clipboard-check': clipboard_check,
  'clipboard-copy': clipboard_copy,
  'clipboard-cross': clipboard_cross,
  'clipboard-notes': clipboard_notes,
  'clipboard-remove': clipboard_remove,
  clock: clock,
  close: close,
  cloud: cloud,
  'cloud-disconnect': cloud_disconnect,
  'cloud-download': cloud_download,
  'cloud-download-alt': cloud_download_alt,
  'cloud-upload': cloud_upload,
  'cloud-upload-alt': cloud_upload_alt,
  code: code,
  coffee: coffee,
  coin: coin,
  coins: coins,
  compass: compass,
  'component-add': component_add,
  contacts: contacts,
  contract: contract,
  create: create,
  'credit-card': credit_card,
  crop: crop,
  cross: cross,
  'cross-circle': cross_circle,
  crosshair: crosshair,
  cube: cube,
  cubes: cubes,
  cylinder: cylinder,
  database: database,
  diamond: diamond,
  directions: directions,
  disc: disc,
  display: display,
  'display-alt': display_alt,
  document: document,
  'document-justified': document_justified,
  'document-list': document_list,
  'document-stack': document_stack,
  'document-words': document_words,
  door: door,
  'door-alt': door_alt,
  download: download,
  'download-alt': download_alt,
  downward: downward,
  drag: drag,
  'drag-circle': drag_circle,
  'drag-vertical': drag_vertical,
  duplicate: duplicate,
  'duplicate-alt': duplicate_alt,
  enter: enter,
  'enter-alt': enter_alt,
  episodes: episodes,
  'exit-left': exit_left,
  'exit-right': exit_right,
  expand: expand,
  'expand-height': expand_height,
  'expand-width': expand_width,
  external: external,
  eye: eye,
  'eye-closed': eye_closed,
  'eye-no': eye_no,
  'face-delighted': face_delighted,
  'face-happy': face_happy,
  'face-neutral': face_neutral,
  'face-sad': face_sad,
  'file-download': file_download,
  'file-upload': file_upload,
  'files-history': files_history,
  'files-multi': files_multi,
  'files-stack': files_stack,
  film: film,
  filter: filter,
  'filter-circle': filter_circle,
  'filter-single': filter_single,
  filtering: filtering,
  fingerprint: fingerprint,
  flag: flag,
  flame: flame,
  'flame-alt': flame_alt,
  'flip-view': flip_view,
  floppy: floppy,
  'folder-add': folder_add,
  'folder-closed': folder_closed,
  'folder-minus': folder_minus,
  'folder-open': folder_open,
  'fork-git': fork_git,
  forward: forward,
  frame: frame,
  fullscreen: fullscreen,
  funnel: funnel,
  gauge: gauge,
  gift: gift,
  globe: globe,
  gps: gps,
  grab: grab,
  'graph-bar': graph_bar,
  'graph-box': graph_box,
  'graph-increase': graph_increase,
  grid: grid,
  'grid-circles': grid_circles,
  'grid-circles-add': grid_circles_add,
  'grid-small': grid_small,
  'grid-squares': grid_squares,
  'grid-squares-add': grid_squares_add,
  hand: hand,
  harddrive: harddrive,
  hash: hash,
  heart: heart,
  'heart-rate': heart_rate,
  'heart-remove': heart_remove,
  height: height,
  hierarchy: hierarchy,
  home: home,
  'home-alt': home_alt,
  'home-check': home_check,
  'home-door': home_door,
  import: _import,
  inbox: inbox,
  'inbox-alt': inbox_alt,
  'info-circle': info_circle,
  'iphone-landscape': iphone_landscape,
  'iphone-portrait': iphone_portrait,
  'jump-backward': jump_backward,
  'jump-forward': jump_forward,
  'jump-left': jump_left,
  'jump-right': jump_right,
  keyboard: keyboard,
  laptop: laptop,
  lightbulb: lightbulb,
  'lightbulb-on': lightbulb_on,
  lightning: lightning,
  'lightning-alt': lightning_alt,
  lineweight: lineweight,
  link: link,
  'link-alt': link_alt,
  'link-broken': link_broken,
  'link-horizontal': link_horizontal,
  'link-vertical': link_vertical,
  list: list,
  'list-add': list_add,
  'list-numbered': list_numbered,
  loader: loader,
  location: location,
  lock: lock,
  'lock-open': lock_open,
  mail: mail,
  'mail-add': mail_add,
  'mail-delete': mail_delete,
  'mail-minus': mail_minus,
  'mail-new': mail_new,
  'mail-open': mail_open,
  'mail-remove': mail_remove,
  marquee: marquee,
  maximise: maximise,
  'menu-hamburger': menu_hamburger,
  'menu-horizontal': menu_horizontal,
  'menu-vertical': menu_vertical,
  message: message,
  'message-writing': message_writing,
  microphone: microphone,
  'microphone-disabled': microphone_disabled,
  'microphone-muted': microphone_muted,
  midpoint: midpoint,
  'mini-player': mini_player,
  minimise: minimise,
  minus: minus,
  'minus-circle': minus_circle,
  moon: moon,
  move: move,
  newspaper: newspaper,
  'no-sign': no_sign,
  notebook: notebook,
  notification: notification,
  nut: nut,
  pages: pages,
  'panel-bottom': panel_bottom,
  'panel-center': panel_center,
  'panel-left': panel_left,
  'panel-right': panel_right,
  'panel-sectioned': panel_sectioned,
  'panel-top': panel_top,
  paper: paper,
  'paper-folded': paper_folded,
  'paper-plane': paper_plane,
  'paper-plane-alt': paper_plane_alt,
  paperclip: paperclip,
  'paragraph-center': paragraph_center,
  'paragraph-end': paragraph_end,
  'paragraph-left': paragraph_left,
  'paragraph-right': paragraph_right,
  'paragraph-start': paragraph_start,
  pen: pen,
  'phone-landscape': phone_landscape,
  'phone-portrait': phone_portrait,
  picture: picture,
  'pie-half': pie_half,
  'pie-quarter': pie_quarter,
  'pie-third': pie_third,
  pill: pill,
  'play-button': play_button,
  plus: plus,
  'plus-circle': plus_circle,
  postcard: postcard,
  printer: printer,
  projector: projector,
  'pull-down': pull_down,
  'pull-left': pull_left,
  'pull-right': pull_right,
  'pull-up': pull_up,
  'push-down': push_down,
  'push-left': push_left,
  'push-right': push_right,
  'push-up': push_up,
  'question-circle': question_circle,
  'radio-on': radio_on,
  receipt: receipt,
  record: record,
  redo: redo,
  refresh: refresh,
  'refresh-alt': refresh_alt,
  replicate: replicate,
  'replicate-alt': replicate_alt,
  reset: reset,
  'reset-alt': reset_alt,
  'reset-forward': reset_forward,
  'reset-hard': reset_hard,
  'reset-temporary': reset_temporary,
  retweet: retweet,
  reuse: reuse,
  reverse: reverse,
  'reverse-alt': reverse_alt,
  revert: revert,
  rocket: rocket,
  ruler: ruler,
  scale: scale,
  'scale-contract': scale_contract,
  'scale-extend': scale_extend,
  scalpel: scalpel,
  search: search,
  server: server,
  settings: settings,
  share: share,
  'share-alt': share_alt,
  shuffle: shuffle,
  'side-menu': side_menu,
  'signal-full': signal_full,
  'signal-low': signal_low,
  'signal-medium': signal_medium,
  'signal-none': signal_none,
  'slash-backward': slash_backward,
  'slash-forward': slash_forward,
  sliders: sliders,
  sort: sort,
  'sort-alt': sort_alt,
  speaker: speaker,
  'speech-bubble': speech_bubble,
  'speech-typing': speech_typing,
  split: split,
  'split-three': split_three,
  star: star,
  sun: sun,
  support: support,
  swap: swap,
  switch: _switch,
  table: table,
  'table-header': table_header,
  tag: tag,
  'tag-milestone': tag_milestone,
  tags: tags,
  target: target,
  terminal: terminal,
  thread: thread,
  'thumbs-down': thumbs_down,
  'thumbs-up': thumbs_up,
  ticket: ticket,
  timeline: timeline,
  todo: todo,
  toggle: toggle,
  toggles: toggles,
  translate: translate,
  trash: trash,
  'trash-alt': trash_alt,
  trophy: trophy,
  'tv-mode': tv_mode,
  unarchive: unarchive,
  undo: undo,
  'undo-history': undo_history,
  'unlink-horizontal': unlink_horizontal,
  'unlink-vertical': unlink_vertical,
  upload: upload,
  'upload-alt': upload_alt,
  upward: upward,
  user: user,
  'user-add': user_add,
  'user-circle': user_circle,
  'user-male': user_male,
  'user-male-circle': user_male_circle,
  'user-remove': user_remove,
  users: users,
  venn: venn,
  version: version,
  versions: versions,
  video: video,
  'volume-0': volume_0,
  'volume-add': volume_add,
  'volume-disabled': volume_disabled,
  'volume-high': volume_high,
  'volume-low': volume_low,
  'volume-minus': volume_minus,
  'volume-muted': volume_muted,
  wallet: wallet,
  'warning-circle': warning_circle,
  'warning-hex': warning_hex,
  'warning-triangle': warning_triangle,
  waves: waves,
  width: width,
  wifi: wifi,
  'wifi-error': wifi_error,
  'wifi-none': wifi_none,
  window: window,
  'window-collapse-left': window_collapse_left,
  'window-collapse-right': window_collapse_right,
  'window-content': window_content,
  'wrap-back': wrap_back,
  'wrap-forward': wrap_forward,
  write: write,
  'zoom-cancel': zoom_cancel,
  'zoom-in': zoom_in,
  'zoom-out': zoom_out,
  'zoom-reset': zoom_reset,
};

/**
 * Union type of all available icon names
 */
export type IconName =
  | 'airplay'
  | 'alarm-clock'
  | 'align-horizontal'
  | 'align-vertical'
  | 'angle'
  | 'archive'
  | 'arrow-bottom-left'
  | 'arrow-bottom-right'
  | 'arrow-down'
  | 'arrow-down-circle'
  | 'arrow-left'
  | 'arrow-left-circle'
  | 'arrow-right'
  | 'arrow-right-circle'
  | 'arrow-top-left'
  | 'arrow-top-right'
  | 'arrow-up'
  | 'arrow-up-circle'
  | 'audio-wave'
  | 'backspace'
  | 'backward'
  | 'bag'
  | 'battery-75'
  | 'battery-charging'
  | 'battery-empty'
  | 'battery-full'
  | 'battery-half'
  | 'battery-low'
  | 'bell'
  | 'bell-disabled'
  | 'bell-ringing'
  | 'bell-snooze'
  | 'bluetooth'
  | 'book'
  | 'book-closed'
  | 'book-text'
  | 'bookmark'
  | 'bookmark-book'
  | 'box'
  | 'box-add'
  | 'box-download'
  | 'box-open'
  | 'box-remove'
  | 'boxes'
  | 'branch'
  | 'briefcase'
  | 'browser'
  | 'browser-alt'
  | 'button-add'
  | 'button-minus'
  | 'calculator'
  | 'calendar'
  | 'calendar-add'
  | 'calendar-date'
  | 'calendar-day'
  | 'calendar-days'
  | 'calendar-last-day'
  | 'calendar-month'
  | 'calendar-move'
  | 'calendar-remove'
  | 'calendar-split'
  | 'calendar-week'
  | 'camera'
  | 'camera-alt'
  | 'camera-noflash'
  | 'camera-noflash-alt'
  | 'capture'
  | 'card-timeline'
  | 'card-view'
  | 'carousel'
  | 'cart'
  | 'cast'
  | 'chain'
  | 'chat-add'
  | 'check'
  | 'check-circle'
  | 'check-circle-outside'
  | 'checkbox-checked'
  | 'checkbox-empty'
  | 'chevron-close'
  | 'chevron-down'
  | 'chevron-down-circle'
  | 'chevron-down-double'
  | 'chevron-left'
  | 'chevron-left-circle'
  | 'chevron-left-double'
  | 'chevron-open'
  | 'chevron-right'
  | 'chevron-right-circle'
  | 'chevron-right-double'
  | 'chevron-up'
  | 'chevron-up-circle'
  | 'chevron-up-double'
  | 'circle'
  | 'circle-menu'
  | 'circle-split'
  | 'clipboard'
  | 'clipboard-add'
  | 'clipboard-check'
  | 'clipboard-copy'
  | 'clipboard-cross'
  | 'clipboard-notes'
  | 'clipboard-remove'
  | 'clock'
  | 'close'
  | 'cloud'
  | 'cloud-disconnect'
  | 'cloud-download'
  | 'cloud-download-alt'
  | 'cloud-upload'
  | 'cloud-upload-alt'
  | 'code'
  | 'coffee'
  | 'coin'
  | 'coins'
  | 'compass'
  | 'component-add'
  | 'contacts'
  | 'contract'
  | 'create'
  | 'credit-card'
  | 'crop'
  | 'cross'
  | 'cross-circle'
  | 'crosshair'
  | 'cube'
  | 'cubes'
  | 'cylinder'
  | 'database'
  | 'diamond'
  | 'directions'
  | 'disc'
  | 'display'
  | 'display-alt'
  | 'document'
  | 'document-justified'
  | 'document-list'
  | 'document-stack'
  | 'document-words'
  | 'door'
  | 'door-alt'
  | 'download'
  | 'download-alt'
  | 'downward'
  | 'drag'
  | 'drag-circle'
  | 'drag-vertical'
  | 'duplicate'
  | 'duplicate-alt'
  | 'enter'
  | 'enter-alt'
  | 'episodes'
  | 'exit-left'
  | 'exit-right'
  | 'expand'
  | 'expand-height'
  | 'expand-width'
  | 'external'
  | 'eye'
  | 'eye-closed'
  | 'eye-no'
  | 'face-delighted'
  | 'face-happy'
  | 'face-neutral'
  | 'face-sad'
  | 'file-download'
  | 'file-upload'
  | 'files-history'
  | 'files-multi'
  | 'files-stack'
  | 'film'
  | 'filter'
  | 'filter-circle'
  | 'filter-single'
  | 'filtering'
  | 'fingerprint'
  | 'flag'
  | 'flame'
  | 'flame-alt'
  | 'flip-view'
  | 'floppy'
  | 'folder-add'
  | 'folder-closed'
  | 'folder-minus'
  | 'folder-open'
  | 'fork-git'
  | 'forward'
  | 'frame'
  | 'fullscreen'
  | 'funnel'
  | 'gauge'
  | 'gift'
  | 'globe'
  | 'gps'
  | 'grab'
  | 'graph-bar'
  | 'graph-box'
  | 'graph-increase'
  | 'grid'
  | 'grid-circles'
  | 'grid-circles-add'
  | 'grid-small'
  | 'grid-squares'
  | 'grid-squares-add'
  | 'hand'
  | 'harddrive'
  | 'hash'
  | 'heart'
  | 'heart-rate'
  | 'heart-remove'
  | 'height'
  | 'hierarchy'
  | 'home'
  | 'home-alt'
  | 'home-check'
  | 'home-door'
  | 'import'
  | 'inbox'
  | 'inbox-alt'
  | 'info-circle'
  | 'iphone-landscape'
  | 'iphone-portrait'
  | 'jump-backward'
  | 'jump-forward'
  | 'jump-left'
  | 'jump-right'
  | 'keyboard'
  | 'laptop'
  | 'lightbulb'
  | 'lightbulb-on'
  | 'lightning'
  | 'lightning-alt'
  | 'lineweight'
  | 'link'
  | 'link-alt'
  | 'link-broken'
  | 'link-horizontal'
  | 'link-vertical'
  | 'list'
  | 'list-add'
  | 'list-numbered'
  | 'loader'
  | 'location'
  | 'lock'
  | 'lock-open'
  | 'mail'
  | 'mail-add'
  | 'mail-delete'
  | 'mail-minus'
  | 'mail-new'
  | 'mail-open'
  | 'mail-remove'
  | 'marquee'
  | 'maximise'
  | 'menu-hamburger'
  | 'menu-horizontal'
  | 'menu-vertical'
  | 'message'
  | 'message-writing'
  | 'microphone'
  | 'microphone-disabled'
  | 'microphone-muted'
  | 'midpoint'
  | 'mini-player'
  | 'minimise'
  | 'minus'
  | 'minus-circle'
  | 'moon'
  | 'move'
  | 'newspaper'
  | 'no-sign'
  | 'notebook'
  | 'notification'
  | 'nut'
  | 'pages'
  | 'panel-bottom'
  | 'panel-center'
  | 'panel-left'
  | 'panel-right'
  | 'panel-sectioned'
  | 'panel-top'
  | 'paper'
  | 'paper-folded'
  | 'paper-plane'
  | 'paper-plane-alt'
  | 'paperclip'
  | 'paragraph-center'
  | 'paragraph-end'
  | 'paragraph-left'
  | 'paragraph-right'
  | 'paragraph-start'
  | 'pen'
  | 'phone-landscape'
  | 'phone-portrait'
  | 'picture'
  | 'pie-half'
  | 'pie-quarter'
  | 'pie-third'
  | 'pill'
  | 'play-button'
  | 'plus'
  | 'plus-circle'
  | 'postcard'
  | 'printer'
  | 'projector'
  | 'pull-down'
  | 'pull-left'
  | 'pull-right'
  | 'pull-up'
  | 'push-down'
  | 'push-left'
  | 'push-right'
  | 'push-up'
  | 'question-circle'
  | 'radio-on'
  | 'receipt'
  | 'record'
  | 'redo'
  | 'refresh'
  | 'refresh-alt'
  | 'replicate'
  | 'replicate-alt'
  | 'reset'
  | 'reset-alt'
  | 'reset-forward'
  | 'reset-hard'
  | 'reset-temporary'
  | 'retweet'
  | 'reuse'
  | 'reverse'
  | 'reverse-alt'
  | 'revert'
  | 'rocket'
  | 'ruler'
  | 'scale'
  | 'scale-contract'
  | 'scale-extend'
  | 'scalpel'
  | 'search'
  | 'server'
  | 'settings'
  | 'share'
  | 'share-alt'
  | 'shuffle'
  | 'side-menu'
  | 'signal-full'
  | 'signal-low'
  | 'signal-medium'
  | 'signal-none'
  | 'slash-backward'
  | 'slash-forward'
  | 'sliders'
  | 'sort'
  | 'sort-alt'
  | 'speaker'
  | 'speech-bubble'
  | 'speech-typing'
  | 'split'
  | 'split-three'
  | 'star'
  | 'sun'
  | 'support'
  | 'swap'
  | 'switch'
  | 'table'
  | 'table-header'
  | 'tag'
  | 'tag-milestone'
  | 'tags'
  | 'target'
  | 'terminal'
  | 'thread'
  | 'thumbs-down'
  | 'thumbs-up'
  | 'ticket'
  | 'timeline'
  | 'todo'
  | 'toggle'
  | 'toggles'
  | 'translate'
  | 'trash'
  | 'trash-alt'
  | 'trophy'
  | 'tv-mode'
  | 'unarchive'
  | 'undo'
  | 'undo-history'
  | 'unlink-horizontal'
  | 'unlink-vertical'
  | 'upload'
  | 'upload-alt'
  | 'upward'
  | 'user'
  | 'user-add'
  | 'user-circle'
  | 'user-male'
  | 'user-male-circle'
  | 'user-remove'
  | 'users'
  | 'venn'
  | 'version'
  | 'versions'
  | 'video'
  | 'volume-0'
  | 'volume-add'
  | 'volume-disabled'
  | 'volume-high'
  | 'volume-low'
  | 'volume-minus'
  | 'volume-muted'
  | 'wallet'
  | 'warning-circle'
  | 'warning-hex'
  | 'warning-triangle'
  | 'waves'
  | 'width'
  | 'wifi'
  | 'wifi-error'
  | 'wifi-none'
  | 'window'
  | 'window-collapse-left'
  | 'window-collapse-right'
  | 'window-content'
  | 'wrap-back'
  | 'wrap-forward'
  | 'write'
  | 'zoom-cancel'
  | 'zoom-in'
  | 'zoom-out'
  | 'zoom-reset';

/**
 * Get an icon template by name
 * @param name - Icon name from the registry
 * @returns Lit template with SVG content, or null if not found
 */
export function getIcon(name: string): TemplateResult | null {
  const svgContent = iconRegistry[name];
  if (!svgContent) {
    return null;
  }
  return html`${unsafeHTML(svgContent)}`;
}

/**
 * Get all available icon names
 * @returns Array of all icon names in the registry
 */
export function getAllIconNames(): IconName[] {
  return Object.keys(iconRegistry) as IconName[];
}
